language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-node' ]; then cd .. && eval "mv $currentfolder generator-node" && cd generator-node; fi

